# action.yml
name: CI

description: 'CI Action'

inputs:
  src_path:
    description: Path of source (relative path from /github/workspace)
    required: true
  github_token:
    description: github_token
    required: true
  email_token:
    description: Email token
    required: true
  patchwork_token:
    description: Patchwork token
    required: true
  config:
    description: Configuration file or URL
    required: false
    default: /config.ini
  email_message:
    description: Email message file or URL
    required: false
    default: /default-email-message.txt

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src_path }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    EMAIL_TOKEN: ${{ inputs.email_token }}
    PATCHWORK_TOKEN: ${{ inputs.patchwork_token }}
    CONFIG: ${{ inputs.config }}
    EMAIL: ${{ inputs.email_message }}
